-- Populate Properties for Nigerian Real Estate Platform
-- This script adds sample properties in various Nigerian locations
-- Run this in Supabase SQL Editor

-- IMPORTANT: 
-- 1. If you get constraint errors, run UPDATE_ALL_CONSTRAINTS.sql FIRST
--    This updates both property_type and listing_type constraints to support Shortlet and Airbnb
-- 2. This script will use the first seller/agent user ID found in your profiles table
-- 3. If no seller/agent exists, properties will be created with created_by = NULL
-- 4. To use a specific user, replace (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1) with the UUID

-- ============================================
-- ABUJA PROPERTIES
-- ============================================

INSERT INTO public.properties (
  title, description, price, currency, property_type, listing_type,
  location, state, city, address, bedrooms, bathrooms, sqm, parking, year_built,
  images, features, amenities, verification_status, is_featured, is_active, created_by
) VALUES
-- Abuja - Sale
(
  'Luxury 5-Bedroom Duplex in Maitama',
  'Beautiful modern duplex with state-of-the-art facilities. Located in the prestigious Maitama district. Features include: fully fitted kitchen, ensuite bedrooms, study room, guest quarters, and ample parking space. Perfect for executives and diplomats.',
  85000000,
  'NGN',
  'House',
  'sale',
  'Maitama',
  'FCT',
  'Abuja',
  'Plot 123, Maitama District, Abuja',
  5,
  5.5,
  450,
  4,
  2020,
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
  ARRAY['Modern Design', 'Fully Furnished', 'Security System', 'Generator', 'Water Supply'],
  ARRAY['Swimming Pool', 'Gym', 'Playground', '24/7 Security', 'Parking'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
(
  '3-Bedroom Apartment in Wuse 2',
  'Spacious 3-bedroom apartment in the heart of Wuse 2. Close to shopping centers, schools, and business districts. Well-maintained building with 24/7 security.',
  45000000,
  'NGN',
  'Apartment',
  'sale',
  'Wuse 2',
  'FCT',
  'Abuja',
  'Block 45, Wuse 2, Abuja',
  3,
  3,
  180,
  2,
  2018,
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  ARRAY['Fully Furnished', 'Air Conditioning', 'Elevator', 'Security'],
  ARRAY['Parking', '24/7 Security', 'Nearby Shopping'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Abuja - Rent
(
  '4-Bedroom Semi-Detached in Garki',
  'Beautiful semi-detached house available for rent. Well-furnished with modern amenities. Quiet neighborhood, perfect for families.',
  2500000,
  'NGN',
  'House',
  'rent',
  'Garki',
  'FCT',
  'Abuja',
  'Area 2, Garki, Abuja',
  4,
  4,
  280,
  3,
  2019,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply', 'Security'],
  ARRAY['Parking', 'Security', 'Quiet Neighborhood'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Abuja - Shortlet
(
  'Luxury Shortlet Apartment in Asokoro',
  'Premium shortlet apartment in Asokoro. Fully serviced, daily cleaning, WiFi, and all modern amenities. Perfect for business travelers and tourists.',
  45000,
  'NGN',
  'Shortlet',
  'short_stay',
  'Asokoro',
  'FCT',
  'Abuja',
  'Asokoro District, Abuja',
  2,
  2,
  120,
  1,
  2021,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Daily Cleaning', 'Air Conditioning'],
  ARRAY['24/7 Security', 'Parking', 'Nearby Restaurants'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- LAGOS PROPERTIES
-- ============================================

-- Lagos - Sale
(
  '5-Bedroom Luxury Villa in Lekki Phase 1',
  'Stunning modern villa with ocean view. Located in the exclusive Lekki Phase 1. Features include: private pool, gym, home theater, and smart home system.',
  120000000,
  'NGN',
  'House',
  'sale',
  'Lekki Phase 1',
  'Lagos',
  'Lagos',
  'Plot 15, Admiralty Way, Lekki Phase 1',
  5,
  6,
  550,
  5,
  2022,
  ARRAY['https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800', 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800'],
  ARRAY['Ocean View', 'Smart Home', 'Private Pool', 'Home Theater', 'Gym'],
  ARRAY['Swimming Pool', 'Gym', 'Home Theater', '24/7 Security', 'Parking'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
(
  '3-Bedroom Apartment in Victoria Island',
  'Modern apartment in the heart of Victoria Island. Close to business district, shopping malls, and beaches. High-rise building with stunning city views.',
  65000000,
  'NGN',
  'Apartment',
  'sale',
  'Victoria Island',
  'Lagos',
  'Lagos',
  'Block 12, Victoria Island, Lagos',
  3,
  3,
  200,
  2,
  2020,
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
  ARRAY['City View', 'Fully Furnished', 'Elevator', 'Security'],
  ARRAY['Parking', '24/7 Security', 'Nearby Shopping', 'Beach Access'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Lagos - Rent
(
  '2-Bedroom Flat in Ikeja',
  'Cozy 2-bedroom flat in Ikeja. Well-maintained, close to airport and business district. Perfect for young professionals.',
  1200000,
  'NGN',
  'Apartment',
  'rent',
  'Ikeja',
  'Lagos',
  'Lagos',
  'Allen Avenue, Ikeja, Lagos',
  2,
  2,
  100,
  1,
  2017,
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  ARRAY['Fully Furnished', 'Air Conditioning', 'Generator'],
  ARRAY['Parking', 'Security', 'Near Airport'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Lagos - Shortlet
(
  'Luxury Shortlet in Ikoyi',
  'Premium shortlet apartment in Ikoyi. Fully serviced with daily housekeeping. Perfect location for business and leisure.',
  55000,
  'NGN',
  'Shortlet',
  'short_stay',
  'Ikoyi',
  'Lagos',
  'Lagos',
  'Ikoyi, Lagos',
  2,
  2,
  110,
  1,
  2021,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Daily Cleaning', 'Air Conditioning'],
  ARRAY['24/7 Security', 'Parking', 'Nearby Restaurants'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Lagos - Commercial
(
  'Office Space for Rent in Lekki',
  'Modern office space available for rent. 500sqm, fully air-conditioned, with parking facilities. Perfect for corporate offices.',
  3500000,
  'NGN',
  'Commercial',
  'rent',
  'Lekki',
  'Lagos',
  'Lagos',
  'Lekki Phase 1, Lagos',
  NULL,
  4,
  500,
  10,
  2019,
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
  ARRAY['Air Conditioning', 'Elevator', 'Parking', 'Security'],
  ARRAY['Parking', '24/7 Security', 'Nearby Restaurants'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- PORT HARCOURT PROPERTIES
-- ============================================

-- Port Harcourt - Sale
(
  '4-Bedroom Duplex in GRA Phase 2',
  'Beautiful duplex in the Government Reserved Area. Well-maintained with modern facilities. Quiet and secure neighborhood.',
  55000000,
  'NGN',
  'House',
  'sale',
  'GRA Phase 2',
  'Rivers',
  'Port Harcourt',
  'GRA Phase 2, Port Harcourt',
  4,
  4,
  350,
  3,
  2018,
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply', 'Security'],
  ARRAY['Parking', 'Security', 'Quiet Neighborhood'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Port Harcourt - Rent
(
  '3-Bedroom Bungalow in Woji',
  'Spacious 3-bedroom bungalow available for rent. Well-furnished, close to schools and shopping centers.',
  1800000,
  'NGN',
  'House',
  'rent',
  'Woji',
  'Rivers',
  'Port Harcourt',
  'Woji, Port Harcourt',
  3,
  3,
  220,
  2,
  2016,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply'],
  ARRAY['Parking', 'Security'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Port Harcourt - Shortlet
(
  'Executive Shortlet in Trans Amadi',
  'Modern shortlet apartment in Trans Amadi. Perfect for business travelers. Fully serviced with all amenities.',
  35000,
  'NGN',
  'Shortlet',
  'short_stay',
  'Trans Amadi',
  'Rivers',
  'Port Harcourt',
  'Trans Amadi, Port Harcourt',
  2,
  2,
  100,
  1,
  2020,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Daily Cleaning'],
  ARRAY['24/7 Security', 'Parking'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- BENIN CITY PROPERTIES
-- ============================================

-- Benin City - Sale
(
  '4-Bedroom Duplex in GRA',
  'Modern duplex in Government Reserved Area, Benin City. Well-designed with quality finishes. Perfect for families.',
  42000000,
  'NGN',
  'House',
  'sale',
  'GRA',
  'Edo',
  'Benin City',
  'GRA, Benin City',
  4,
  4,
  320,
  3,
  2019,
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply', 'Security'],
  ARRAY['Parking', 'Security', 'Quiet Neighborhood'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Benin City - Rent
(
  '3-Bedroom Flat in Ugbowo',
  'Comfortable 3-bedroom flat in Ugbowo. Close to University of Benin. Well-maintained and affordable.',
  800000,
  'NGN',
  'Apartment',
  'rent',
  'Ugbowo',
  'Edo',
  'Benin City',
  'Ugbowo, Benin City',
  3,
  2,
  150,
  1,
  2015,
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  ARRAY['Fully Furnished', 'Generator'],
  ARRAY['Parking', 'Security'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- EDO STATE PROPERTIES (Other locations)
-- ============================================

-- Edo State - Land
(
  'Land for Sale in Auchi',
  'Prime land for sale in Auchi, Edo State. 500sqm plot, suitable for residential or commercial development. Clear title documents.',
  15000000,
  'NGN',
  'Land',
  'sale',
  'Auchi',
  'Edo',
  'Auchi',
  'Auchi, Edo State',
  NULL,
  NULL,
  500,
  0,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
  ARRAY['Clear Title', 'Surveyed', 'Access Road'],
  ARRAY['Nearby Infrastructure'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- DELTA STATE PROPERTIES
-- ============================================

-- Delta State - Sale
(
  '5-Bedroom Mansion in Asaba',
  'Luxury 5-bedroom mansion in Asaba, Delta State. Modern design with premium finishes. Perfect for high-end living.',
  75000000,
  'NGN',
  'House',
  'sale',
  'Asaba',
  'Delta',
  'Asaba',
  'GRA, Asaba, Delta State',
  5,
  6,
  480,
  4,
  2021,
  ARRAY['https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800'],
  ARRAY['Luxury Finishes', 'Private Pool', 'Generator', 'Security'],
  ARRAY['Swimming Pool', 'Parking', '24/7 Security'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Delta State - Rent
(
  '3-Bedroom Apartment in Warri',
  'Modern 3-bedroom apartment in Warri. Well-furnished, close to business district and shopping centers.',
  1500000,
  'NGN',
  'Apartment',
  'rent',
  'Warri',
  'Delta',
  'Warri',
  'Effurun, Warri, Delta State',
  3,
  3,
  180,
  2,
  2018,
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Air Conditioning'],
  ARRAY['Parking', 'Security'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- KADUNA PROPERTIES
-- ============================================

-- Kaduna - Sale
(
  '4-Bedroom Duplex in Barnawa',
  'Beautiful 4-bedroom duplex in Barnawa, Kaduna. Well-maintained with modern amenities. Secure and quiet neighborhood.',
  48000000,
  'NGN',
  'House',
  'sale',
  'Barnawa',
  'Kaduna',
  'Kaduna',
  'Barnawa, Kaduna',
  4,
  4,
  340,
  3,
  2017,
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply', 'Security'],
  ARRAY['Parking', 'Security', 'Quiet Neighborhood'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kaduna - Rent
(
  '3-Bedroom Bungalow in Malali',
  'Spacious 3-bedroom bungalow available for rent in Malali. Well-furnished and affordable.',
  900000,
  'NGN',
  'House',
  'rent',
  'Malali',
  'Kaduna',
  'Kaduna',
  'Malali, Kaduna',
  3,
  3,
  200,
  2,
  2015,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
  ARRAY['Fully Furnished', 'Generator'],
  ARRAY['Parking', 'Security'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kaduna - Shortlet
(
  'Executive Shortlet in Kaduna North',
  'Modern shortlet apartment in Kaduna North. Perfect for business travelers. Fully serviced.',
  30000,
  'NGN',
  'Shortlet',
  'short_stay',
  'Kaduna North',
  'Kaduna',
  'Kaduna',
  'Kaduna North, Kaduna',
  2,
  2,
  95,
  1,
  2020,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Daily Cleaning'],
  ARRAY['24/7 Security', 'Parking'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- KANO PROPERTIES
-- ============================================

-- Kano - Sale
(
  '5-Bedroom Duplex in GRA',
  'Luxury 5-bedroom duplex in GRA, Kano. Modern design with premium finishes. Perfect for large families.',
  65000000,
  'NGN',
  'House',
  'sale',
  'GRA',
  'Kano',
  'Kano',
  'GRA, Kano',
  5,
  5,
  420,
  4,
  2020,
  ARRAY['https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800'],
  ARRAY['Luxury Finishes', 'Generator', 'Water Supply', 'Security'],
  ARRAY['Parking', '24/7 Security', 'Quiet Neighborhood'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kano - Rent
(
  '4-Bedroom House in Nassarawa',
  'Spacious 4-bedroom house available for rent in Nassarawa. Well-maintained and affordable.',
  1200000,
  'NGN',
  'House',
  'rent',
  'Nassarawa',
  'Kano',
  'Kano',
  'Nassarawa, Kano',
  4,
  4,
  280,
  2,
  2016,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
  ARRAY['Fully Furnished', 'Generator', 'Water Supply'],
  ARRAY['Parking', 'Security'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kano - Commercial
(
  'Shop Space for Rent in Sabon Gari',
  'Prime shop space in Sabon Gari market area. High foot traffic, perfect for retail business. 50sqm.',
  250000,
  'NGN',
  'Commercial',
  'rent',
  'Sabon Gari',
  'Kano',
  'Kano',
  'Sabon Gari, Kano',
  NULL,
  1,
  50,
  0,
  2010,
  ARRAY['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
  ARRAY['High Traffic', 'Prime Location'],
  ARRAY['Nearby Market', 'Parking Available'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),

-- ============================================
-- AIRBNB PROPERTIES (All Locations)
-- ============================================

-- Abuja - Airbnb
(
  'Luxury Airbnb Apartment in Wuse 2',
  'Beautiful fully furnished Airbnb apartment in the heart of Wuse 2. Perfect for tourists and business travelers. Features include: WiFi, air conditioning, fully equipped kitchen, and 24/7 security. Close to shopping centers and restaurants.',
  55000,
  'NGN',
  'Airbnb',
  'airbnb',
  'Wuse 2',
  'FCT',
  'Abuja',
  'Block 12, Wuse 2, Abuja',
  2,
  2,
  110,
  1,
  2021,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Air Conditioning', 'Kitchen', 'Daily Cleaning'],
  ARRAY['24/7 Security', 'Parking', 'Nearby Shopping', 'Restaurants'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Lagos - Airbnb
(
  'Modern Airbnb Studio in Lekki',
  'Stylish Airbnb studio apartment in Lekki. Perfect for solo travelers or couples. Fully serviced with all modern amenities. Close to beaches and nightlife.',
  45000,
  'NGN',
  'Airbnb',
  'airbnb',
  'Lekki',
  'Lagos',
  'Lagos',
  'Lekki Phase 1, Lagos',
  1,
  1,
  60,
  1,
  2022,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Air Conditioning', 'Kitchenette'],
  ARRAY['24/7 Security', 'Parking', 'Beach Access', 'Nearby Restaurants'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
(
  'Spacious Airbnb Villa in Victoria Island',
  'Luxury 4-bedroom Airbnb villa in Victoria Island. Perfect for families or groups. Features private pool, fully equipped kitchen, and stunning ocean views. Daily housekeeping included.',
  120000,
  'NGN',
  'Airbnb',
  'airbnb',
  'Victoria Island',
  'Lagos',
  'Lagos',
  'Victoria Island, Lagos',
  4,
  4,
  350,
  3,
  2020,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', 'https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800'],
  ARRAY['Private Pool', 'Ocean View', 'Fully Furnished', 'WiFi', 'Daily Cleaning'],
  ARRAY['Swimming Pool', 'Parking', '24/7 Security', 'Beach Access'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Port Harcourt - Airbnb
(
  'Cozy Airbnb Apartment in GRA',
  'Comfortable 2-bedroom Airbnb apartment in GRA, Port Harcourt. Well-furnished with modern amenities. Perfect for business travelers and tourists exploring the city.',
  40000,
  'NGN',
  'Airbnb',
  'airbnb',
  'GRA',
  'Rivers',
  'Port Harcourt',
  'GRA Phase 2, Port Harcourt',
  2,
  2,
  95,
  1,
  2021,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Air Conditioning', 'Kitchen'],
  ARRAY['24/7 Security', 'Parking', 'Quiet Neighborhood'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Benin City - Airbnb
(
  'Modern Airbnb Flat in GRA',
  'Beautiful 3-bedroom Airbnb flat in GRA, Benin City. Fully furnished with all amenities. Great location for exploring the city and nearby attractions.',
  35000,
  'NGN',
  'Airbnb',
  'airbnb',
  'GRA',
  'Edo',
  'Benin City',
  'GRA, Benin City',
  3,
  2,
  130,
  2,
  2020,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Air Conditioning', 'Kitchen'],
  ARRAY['Parking', 'Security', 'Quiet Area'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Delta State - Airbnb
(
  'Luxury Airbnb Mansion in Asaba',
  'Stunning 5-bedroom Airbnb mansion in Asaba. Perfect for large groups or families. Features include: private pool, game room, fully equipped kitchen, and beautiful garden. Daily housekeeping and concierge service.',
  150000,
  'NGN',
  'Airbnb',
  'airbnb',
  'Asaba',
  'Delta',
  'Asaba',
  'GRA, Asaba, Delta State',
  5,
  5,
  450,
  4,
  2021,
  ARRAY['https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800'],
  ARRAY['Private Pool', 'Game Room', 'Fully Furnished', 'WiFi', 'Daily Cleaning'],
  ARRAY['Swimming Pool', 'Garden', 'Parking', '24/7 Security'],
  'verified',
  true,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kaduna - Airbnb
(
  'Executive Airbnb Apartment in Barnawa',
  'Modern 2-bedroom Airbnb apartment in Barnawa, Kaduna. Fully serviced with all amenities. Perfect for business travelers and tourists. Close to business district.',
  35000,
  'NGN',
  'Airbnb',
  'airbnb',
  'Barnawa',
  'Kaduna',
  'Kaduna',
  'Barnawa, Kaduna',
  2,
  2,
  100,
  1,
  2021,
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
  ARRAY['Fully Furnished', 'WiFi', 'Air Conditioning', 'Kitchen'],
  ARRAY['24/7 Security', 'Parking', 'Nearby Business District'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
),
-- Kano - Airbnb
(
  'Traditional Airbnb House in GRA',
  'Beautiful 3-bedroom traditional-style Airbnb house in GRA, Kano. Combines modern amenities with traditional architecture. Perfect for experiencing authentic Kano culture.',
  40000,
  'NGN',
  'Airbnb',
  'airbnb',
  'GRA',
  'Kano',
  'Kano',
  'GRA, Kano',
  3,
  3,
  180,
  2,
  2019,
  ARRAY['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
  ARRAY['Traditional Design', 'Fully Furnished', 'WiFi', 'Air Conditioning'],
  ARRAY['Garden', 'Parking', 'Security', 'Cultural Experience'],
  'verified',
  false,
  true,
  (SELECT id FROM public.profiles WHERE user_type IN ('seller', 'agent') LIMIT 1)
);

-- Verify the insertions
SELECT 
  city, 
  state, 
  COUNT(*) as property_count,
  COUNT(CASE WHEN listing_type = 'sale' THEN 1 END) as for_sale,
  COUNT(CASE WHEN listing_type = 'rent' THEN 1 END) as for_rent,
  COUNT(CASE WHEN listing_type = 'short_stay' THEN 1 END) as shortlet,
  COUNT(CASE WHEN listing_type = 'airbnb' THEN 1 END) as airbnb,
  COUNT(CASE WHEN verification_status = 'verified' THEN 1 END) as verified
FROM public.properties
GROUP BY city, state
ORDER BY state, city;

